### ISSUE TITLE
Cloud maps support in vmware.py

### ISSUE THREAD

**Issue by mikepietruszka** [nmadhok/salt#15]
Hello,

Does vmware.py support maps defined in cloud.maps.d directory?

It is possible to feed the following profile file's declarations to a map file? For example:

/etc/salt/cloud.profilesd./centos.conf:

``` yaml
centos:
  provider: vmware-provider
  image: centos6
  clonefrom: centos6

  num_cpus: 2
  memory: 4096
  devices:
    disk:
      Hard disk 1:
        size: 64
    network:
      Network adapter 1:
        name: eth0
        ip: 192.168.1.50
        gateway: [192.168.1.1]
        subnet_mask: 255.255.255.0
        adapter_type: e1000
        switch_type: standard
        summary: eth0
```

into something like /etc/salt/cloud.maps.d/centos.map:

``` yaml
centos:
  - webserver01
    ip: 192.168.1.50
  - webserver02
    ip: 192.168.1.51
```

Thanks,
maschinetheist

**Comment by nmadhok** [comment]
@maschinetheist Yes it does. Your map file doesn't look right. Use the following map file:

```
centos:
  - webserver01
      devices:
        network:
          Network adapter 1:
            name: <Your network name>
            ip: 192.168.1.50
            gateway: [192.168.1.1]
            subnet_mask: 255.255.255.0
            adapter_type: e1000
            switch_type: standard
  - webserver02
      devices:
        network:
          Network adapter 1:
            name: <Your network name>
            ip: 192.168.1.51
            gateway: [192.168.1.1]
            subnet_mask: 255.255.255.0
            adapter_type: e1000
            switch_type: standard
```

For more examples, see https://github.com/saltstack/salt/issues/23416
